name: complete
channels:
  - defaults
dependencies:
  - numpy
  - scipy
  - seaborn
  - flake8
  - matplotlib
  - pandas
  - requests
  - jupyter
  - tensorflow
  - keras
  - scikit-learn
  - ipython
  - plotly
  - pip:
    - colorlog>=4.0.2
    - dataclasses>=0.6
    - globus-sdk>=1.8.0
